---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: tylers-os
description: Latest UBlue With Tweaks

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - nano
      - git
      - distrobox
      - libsecret
      - git-credential-libsecret
      - adw-gtk3-theme
    remove:
      - firefox
      - firefox-langpacks
      - toolbox
      - htop
      - nvtop

  - type: flatpak
    source: local
    install:
      - app.zen_browser.zen
      - re.sonny.Commit
      - org.gtk.Gtk3theme.adw-gtk3
      - org.gtk.Gtk3theme.adw-gtk3-dark

  - type: gschema-overrides

  - type: signing
