name: tylers-os
description: Latest UBlue With Tweaks

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41

modules:
  # copy all files in files/system to the images root folder
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - nano
      - git
      - distrobox
    remove:
      - firefox
      - firefox-langpacks
      - toolbox

  - type: default-flatpaks
    notify: false # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
