name: tylers-os
description: Latest UBlue With Tweaks

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41

modules:
  # copy all files in files/system to the images root folder
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - nano
      - git
      - distrobox
      - libsecret
      - git-credential-libsecret
      - adw-gtk3-theme
    remove:
      - firefox
      - firefox-langpacks
      - toolbox

  - type: offline-flatpaks
    install:
      - app.zen_browser.zen
      - re.sonny.Commit
      - org.gtk.Gtk3theme.adw-gtk3 
      - org.gtk.Gtk3theme.adw-gtk3-dark

  - type: default-flatpaks
    notify: false # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: FlatHub
      install:
        - app.zen_browser.zen
        - re.sonny.Commit
        - org.gtk.Gtk3theme.adw-gtk3 
        - org.gtk.Gtk3theme.adw-gtk3-dark
    user: {} # Also add Flathub user repo, but no user packages

  - type: gschema-overrides

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
