#!/usr/bin/env bash

mapfile -t INSTALL < "/usr/share/tylers-os/flatpaks/install-list"

for APP in $INSTALL; do 
    flatpak install --user --assumeyes --sideload-repo="/usr/share/tylers-os/flatpaks/offline-repo/.ostree/repo"
done
