#!/usr/bin/env bash

FEDORA_FLATPAK_APPS=$(flatpak list --app --columns=application --runtime | grep 'fedora')

for APP in $FEDORA_FLATPAK_APPS; do
    echo "Uninstalling fedora flatpak app $APP"
    flatpak uninstall --assumeyes "$APP"
done

flatpak remote-delete fedora

systemctl disable -f tylers-os-system-post-rebase-setup.service
