#!/usr/bin/env bash

if diff -q "/usr/share/tylers-os/flatpak/install-list-hash" "/usr/share/tylers-os/flatpak/install-list-hash-old" > /dev/null; then
    echo "install list hash and install list hash (old) are the same, nothing has changed"
else
    mapfile -t INSTALL < "/usr/share/tylers-os/flatpak/install-list"
    
    flatpak remote-modify --collection-id="org.flathub.Stable" "flathub"
    
    for APP in ${INSTALL[@]}; do 
        flatpak install --assumeyes --noninteractive --sideload-repo="/usr/share/tylers-os/flatpak/offline-repo/.ostree/repo" flathub $APP
    done

    cat "/usr/share/tylers-os/flatpak/install-list-hash" > "/usr/share/tylers-os/flatpak/install-list-hash-old"
fi
