#!/usr/bin/env bash

mapfile -t INSTALL < "/usr/share/tylers-os/flatpak/install-list"

flatpak remote-modify --collection-id="org.flathub.Stable" "flathub"

for APP in ${INSTALL[@]}; do 
    flatpak install --assumeyes --sideload-repo="/usr/share/tylers-os/flatpak/offline-repo/.ostree/repo" flathub $APP
done

systemctl disable -f tylers-os-post-rebase-setup.service
